last_update = 1678740913219
api_url = "https://api.playit.cloud/agent"
ping_target_addresses = ["23.133.216.1:5530", "ping.ply.gg"]
control_address = "control.ply.gg"
refresh_from_api = true
api_refresh_rate = 5000
secret_key = "b37064d4e3d2d8bee0c0af04e759d91cff1cbcd4db02bc978a48ba01f0c045fd"

[[mappings]]
proto = "both"
tunnel_ip = "147.185.221.223"
tunnel_from_port = 34187
local_ip = "172.16.216.189"
local_port = 5000

[[mappings]]
proto = "both"
tunnel_ip = "147.185.221.211"
tunnel_from_port = 29496
local_ip = "10.110.44.191"
local_port = 5000

[[mappings]]
name = "minecraftserver_bærbar"
proto = "tcp"
tunnel_ip = "147.185.221.212"
tunnel_from_port = 21845
local_port = 25565

[[mappings]]
proto = "tcp"
tunnel_ip = "147.185.221.180"
tunnel_from_port = 53964
local_port = 25565
